services:
  storybook:
    build: .
    ports:
      - "6008:6006"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: yarn storybook --host 0.0.0.0 --no-open

volumes:
  node_modules:
